id: new_devices_tracker
alias: Notify for New devices
trigger:
- platform: event
  event_type: device_tracker_new_device
condition: []
action:
- service: notify.telegram_martijn
  data_template:
    title: New Device Discovered
    message: >
      New device Discovered:
      {{trigger.event.data.host_name}}
      ({{trigger.event.data.entity_id}})