alias: turn_on_IR_hugo_and_start_timer
trigger:
- platform: state  
  entity_id: input_boolean.foscam_hugo_infrared
  to: 'on'
condition: []
action:
- service: timer.start
  entity_id: timer.hugo_presence_detection