---
# This alerts me via telegram when something happens in
# my front yard and nobody is at home
#
alias: frontyard_snapshot_motion
trigger:
  platform: state
  entity_id: binary_sensor.yicam_motion_sensor
  to: 'on'
condition:
  - condition: state
    entity_id: binary_sensor.people_home
    state: 'off'
action:
  - service: notify.telegram_martijn
    data:
      title: Motion in Front Yard
      message: 'Motion detected {{ now().strftime("%H:%M:%S") }}'

