#
#
# https://www.home-assistant.io/docs/authentication/multi-factor-auth/
#
homeassistant:
  name: Home
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  unit_system: metric
  time_zone: Europe/Amsterdam

  # Load packages
  packages: !include_dir_named integrations