alias: detection_floorbedroom_during_silent_hours
trigger:
- platform: state
  entity_id: binary_sensor.foscam_floor_audio
  to: 'on'
- platform: state
  entity_id: binary_sensor.foscam_floor_motion
  to: 'on'
condition:
  condition: and
  conditions:
    - condition: template
      value_template: >-
        {{
          states('sensor.time')+":00"
          >
          states('input_datetime.floor_silent_hours_start')
        }}
    - condition: template
      value_template: >-
        {{
          states('sensor.time')+":00"
          <
          states('input_datetime.floor_silent_hours_end')
        }}
    - condition: state
      entity_id: timer.floor_presence_detection
      state: 'idle'
action:
  - service: timer.start
    entity_id: timer.floor_presence_detection
  - service: notify.all_devices
    data:
      message: Motion Detected in Floor's Bedroom
      data:
        attachment:
          content-type: jpeg
        push:
          category: camera
        entity_id: camera.camera_foscam_floor