alias: detection_floorbedroom_during_silent_hours
trigger:
- platform: state
  entity_id: binary_sensor.foscam_floor_audio
  to: 'on'
- platform: state
  entity_id: binary_sensor.foscam_floor_motion
  to: 'on'
condition:
  condition: and
  conditions:
    - condition: template
      value_template: >-
        {{
        (states('input_datetime.kids_silent_hours_start')
        <
        states('sensor.time')+":00"
        and
        states('sensor.time')+":00" 
        <
        states('input_datetime.house_silent_hours_start'))
        or
        (states('input_datetime.kids_silent_hours_end')
        <
        states('sensor.time')+":00"
        and
        states('sensor.time')+":00" 
        < 
        states('input_datetime.house_silent_hours_end'))
        }}
    - condition: state
      entity_id: timer.floor_presence_detection
      state: idle
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.foscam_floor_infrared
  - delay: 0:05
  - service: notify.all_devices
    data:
      title: "Motion Detected Floor"
      message: "Motion Detected in Floor's Bedroom"
      data:
        sticky: true
        attachment:
          content-type: jpeg
        push:
          category: camera
        entity_id: camera.camera_foscam_floor
