alias: turn_off_IR_floor_when_timer_finished
trigger:
- platform: event
  event_type: timer.finished
  event_data:
    entity_id: timer.floor_presence_detection
condition: []
action:
- service: input_boolean.turn_off
  entity_id: input_boolean.foscam_floor_infrared