---
# This automation turns on the light in the living room at sunset
# of Home Assistant for Hass.io is released.
#
alias: living_room_turn_on_light_at_sunelevation
trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    below: 7.75
condition: []
action:
- service: homeassistant.turn_on
  entity_id: group.living_room