---
# This automation turns off the light in the living room at a specific configured time
# of Home Assistant for Hass.io is released.
#
#
alias: living_room_turn_off_light_at_silent_hour
trigger:
  - platform: template
    value_template: >-
      {{
        states('input_datetime.house_silent_hours_start')
        ==
        states('sensor.time')+":00"
      }}
action:
  service: homeassistant.turn_off
  entity_id: group.living_room