---
# This automation:
#  1. turns on mediaplayer
#  2. selecs NPO2
#  3. and sends a msg
#
# Trigger:
#   1. the television is turned-off
#   2. People at Home is true
#
# When
#   1. Within the silent time
#
#
alias: turn_on_mediaplayer
trigger:
  - platform: state
    entity_id: device_tracker.philips_television
    to: 'away'
  - platform: state
    entity_id: binary_sensor.people_home
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: template
      value_template: >-
        {{
          states('input_datetime.house_silent_hours_start')
          >
          states('sensor.time')+":00"
        }}
    - condition: template
      value_template: >-
        {{
          states('input_datetime.house_silent_hours_end')
          <
          states('sensor.time')+":00"
        }}
action:
  - service: media_player.turn_on
    entity_id: media_player.woonkamer
  - service: media_player.select_source
    data:
      entity_id: media_player.woonkamer
      source: NPO Radio 2
      volume_level: 0.3
  - service: notify.martijn
    data_template:
      title: "Media Player"
      message: "{{ trigger.entity_id }} enabled the media player at states('sensor.time')."
      data:
        sticky: 'false'
