---
path: automation
title: Automation
icon: mdi:home-automation
cards:
  - type: vertical-stack
    cards:
      - type: entities
        title: Garden
        show_header_toggle: false
        entities:
            - automation.garden_turn_off_light_at_silent_hour
  - type: vertical-stack
    cards:
      - type: entities
        title: Living Room
        show_header_toggle: false
        entities:
            - automation.living_room_turn_on_light_at_sunelevation
            - automation.living_room_turn_off_light_at_silent_hour
            - automation.turn_on_mediaplayer
            - automation.turn_off_mediaplayer
            - automation.turn_off_mediaplayer_at_silent_hour
  - type: vertical-stack
    cards:
      - type: entities
        title: Dining Room
        show_header_toggle: false
        entities:
            - automation.dining_room_turn_on_light_at_sunelevation
            - automation.dining_room_turn_off_light_at_silent_hour
  - type: vertical-stack
    cards:
      - type: entities
        title: Floor Bedroom
        show_header_toggle: false
        entities:
            - automation.detection_floorbedroom_during_silent_hours
            - automation.detection_floorbedroom_during_silent_hours_sound
            - automation.turn_on_ir_floor_and_start_timer
            - automation.turn_off_ir_floor_when_timer_finished
  - type: vertical-stack
    cards:
      - type: entities
        title: Hugo Bedroom
        show_header_toggle: false
        entities:
            - automation.detection_hugobedroom_during_silent_hours
            - automation.detection_hugobedroom_during_silent_hours_sound
            - automation.turn_on_ir_hugo_and_start_timer
            - automation.turn_off_ir_hugo_when_timer_finished
  - type: vertical-stack
    cards:
      - type: entities
        title: Master Bedroom
        show_header_toggle: false
        entities:
            - automation.start_timer_on_turn_on_light_at_master
            - automation.turn_off_light_when_master_timer_finished
  - type: vertical-stack
    cards:
      - type: entities
        title: Bathroom
        show_header_toggle: false
        entities:
            - automation.turn_on_bathroom_light_when_there_is_movement
            - automation.turn_off_bathroom_light_in_the_morning_when_there_is_nomovement
            - automation.turn_off_bathroom_light_in_the_afternoon_when_there_is_nomovement
            - automation.turn_on_ventilator_when_above_threshold
            - automation.turn_off_ventilator_when_timer_finished
            - input_number.bathroom_humidity_humid_threshold
  - type: vertical-stack
    cards:
      - type: entities
        title: Others
        show_header_toggle: false
        entities:
            - automation.leave_creche_in_the_morning
            - automation.enter_creche_in_the_afternoon
            - automation.zone_state_changed_tts
            - automation.leave_work_in_the_afternoon
            - automation.people_not_at_home
            - automation.stookalert_notification
  - type: vertical-stack
    cards:
      - type: entities
        title: System
        show_header_toggle: false
        entities:
            - automation.new_devices_tracker
            - automation.system_upgrade_alert
            - automation.zigbee_map_actualiseren
            - automation.system_low_battery_alert
            - entity: input_datetime.house_silent_hours_start
            - entity: input_datetime.house_silent_hours_end
            - entity: input_datetime.kids_silent_hours_start
            - entity: input_datetime.kids_silent_hours_end