---
path: automation
title: Automation
icon: mdi:home-automation
cards:
  - type: vertical-stack
    cards:
      - type: entities
        show_header_toggle: false
        entities:
            - automation.living_room_turn_on_light_at_sunset
            - automation.living_room_turn_off_light_at_silent_hour
  - type: vertical-stack
    cards:
      - type: entities
        show_header_toggle: false
        entities:
            - automation.dining_room_turn_on_light_at_sunset
            - automation.dining_room_turn_off_light_at_silent_hour
  - type: vertical-stack
    cards:
      - type: entities
        show_header_toggle: false
        entities:
            - automation.start_timer_on_turn_on_light_at_master
            - automation.turn_off_light_when_timer_finished
  - type: vertical-stack
    cards:
      - type: entities
        show_header_toggle: false
        entities:
            - automation.turn_on_bathroom_light_when_there_is_movement
            - automation.turn_off_bathroom_light_in_the_morning_when_there_is_nomovement
            - automation.turn_off_bathroom_light_in_the_afternoon_when_there_is_nomovement
            - automation.turn_on_ventilator_when_above_threshold
            - automation.turn_off_ventilator_when_timer_finished
            - input_number.bathroom_humidity_humid_threshold
  - type: vertical-stack
    cards:
      - type: entities
        show_header_toggle: false
        entities:
            - automation.frontyard_snapshot_motion
  - type: vertical-stack
    cards:
      - type: entities
        show_header_toggle: false
        entities:
            - automation.leave_creche_in_the_morning
            - automation.enter_creche_in_the_afternoon
            - automation.zone_state_changed_tts
  - type: vertical-stack
    cards:
      - type: entities
        show_header_toggle: false
        entities:
            - automation.stookalert_notification
  - type: vertical-stack
    cards:
      - type: entities
        show_header_toggle: false
        entities:
            - automation.system_upgrade_alert
            - automation.zigbee_map_actualiseren
            - automation.system_low_battery_alert
            - entity: input_datetime.house_silent_hours_start
            - entity: input_datetime.house_silent_hours_end