---
#
#
#
# https://www.zigbee2mqtt.io/integration/home_assistant.html
#
# Automation for sending MQTT message on input select change
id: zigbee_log_level
alias: Zigbee2mqtt Log Level
initial_state: "on"
trigger:
  platform: state
  entity_id: input_select.zigbee2mqtt_log_level
action:
  - service: mqtt.publish
    data:
      payload_template: "{{ states('input_select.zigbee2mqtt_log_level') }}"
      topic: zigbee2mqtt/bridge/config/log_level
