---
# this automation is trigger when a stookalert is announced by the RIVM.
#
#
#
alias: stookalert_notification
trigger:
- platform: state
  entity_id: binary_sensor.stookalert
  to: 'on '
condition: []
action:
  - service: notify.telegram_martijn
    data_template:
      title: Stookalert
      message: >-
        Rijksinstituut voor Volksgezondheid en Milieu changed the Stookalert status. 
        Stookalert is {{ states('binary_sensor.stookalert') }}.
      data:
        attachment:
          content-type: jpg
          filename: /config/www/images/fireplace-burning.jpg