description: Weather Rain Notification
alias: weather_rain_notification
trigger:
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - sensor.br_precipitation
      - sensor.br_precipitation_forecast_average
condition:
  - condition: and
    conditions:
      - condition: template
        value_template: >-
          {{
            states('sensor.br_precipitation') > '0.5'
          }}
      - condition: template
        value_template: >-
          {{
            states('input_datetime.house_silent_hours_start')
            >
            states('sensor.time')+":00"
            and
            states('input_datetime.house_silent_hours_end')
            <
            states('sensor.time')+":00"
          }}
action:
  - service: notify.martijn
    data_template:
      title: "Weather Forecast"
      message: "Rain: {{ states('sensor.br_precipitation') }} mm. Forecast: {{ states('sensor.br_precipitation_forecast_average') }}"
