---
# This automation turns off the light when there is no motion in the bathroom 
#
alias: turn_off_bathroom_light_in_the_afternoon_when_there_is_nomovement
trigger:
- platform: state
  entity_id: binary_sensor.0xec1bbdfffeaf9cf0_occupancy
  to: 'off'
condition:
  - condition: time
    after: '12:00:00'
    before: '05:00:00'
action:
- service: light.turn_off
  entity_id: light.upstairs_bathroom
