alias: "Action Turn Lights Off Groundfloor"
initial_state: true
trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: 'Bed Time'
action:
  - service: homeassistant.turn_off
    entity_id: group.living_room
  - service: homeassistant.turn_off
    entity_id: group.dining_room
  - service: homeassistant.turn_off
    entity_id: group.garden
  - service: switch.turn_off
    entity_id: input_boolean.guest_mode
