description: Automate the lighting in bedroom floor
alias: bedroom_floor_light
trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id: switch.lcs01
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.floor_bedroom_light
action:
  choose:
    - conditions:
        - condition: state
          entity_id: switch.lcs01
          state: "on"
        - condition: state
          entity_id: timer.floor_bedroom_light
          state: "idle"
      sequence:
        - service: timer.start
          entity_id: timer.floor_bedroom_light
        - service: homeassistant.turn_on
          entity_id: switch.lcs01
  default:
    - service: homeassistant.turn_off
      entity_id: switch.lcs01
