alias: system_low_battery_alert
trigger:
  - platform: time
    at: '19:00:00'
condition:
  - condition: template
    value_template: >-
      {% for entity_id in states.group.battery_levels.attributes.entity_id if states(entity_id) | int < 20 %}
      {%- if loop.first -%}
      {{ true }}
      {%- endif -%}
      {% endfor %}
action:
  service: script.send_notification
  data_template:
    msg_body: "Low battery detected"
    msg_title: "Low Battery Detected"
