---
# This alerts me on my iPhone when a new release
# of Home Assistant for Hass.io is released.
#
alias: system_upgrade_alert
trigger:
  platform: state
  entity_id: sensor.version_available
condition:
  - condition: template
    value_template: >-
      {{
        states('sensor.version_available')
        !=
        states('sensor.version_current')
      }}
action:
  - service: notify.telegram_martijn
    data_template:
      title: Upgrade time!
      message: >-
        There is a Home Assistant upgrade for Hass.io pending!
        Version {{ states('sensor.version_available') }} just got released!
      data:
        attachment:
          content-type: jpg
          url: https://banner2.cleanpng.com/20180504/esw/kisspng-computer-icons-starburst-clip-art-the-store-to-upgrade-kuangshuai-5aecf79d3a0844.4623510115254793252377.jpg
  - service: persistent_notification.create
    data_template:
      title: Upgrade time!
      message: >-
        There is a Home Assistant upgrade for Hass.io pending!
        Version {{ states('sensor.version_available') }} just got released!
      notification_id: hassio_upgrade
  - service: notify.MARTIJN
    data_template:
      title: Upgrade time!
      message: >-
        There is a Home Assistant upgrade for Hass.io pending!
        Version {{ states('sensor.version_available') }} just got released!
      notification_id: hassio_upgrade