---
# This automation starts the master_room timer when 
# the light is enabled.
#
alias: start_timer_on_turn_on_light_at_master
trigger:
- platform: state
  entity_id: group.master_room, switch.lcs03, switch.lcs04
  from: 'off'
  to: 'on'
condition: []
action:
- service: timer.start
  entity_id: timer.master_room