---
# This automation turns off the ventilator when the humidity is below
# a certain vaue
#
alias: turn_off_ventilator_when_timer_finished
trigger:
- platform: event
  event_type: timer.finished
  event_data:
    entity_id: timer.bathroom_ventilator
condition: []
action:
- service: light.turn_off
  entity_id: light.shelly02_light
