---
# This automation turns on the ventilator when the humidity is above
# a certain vaue
#
alias: turn_on_ventilator_when_above_threshold
trigger:
- platform: state
  entity_id: sensor.bathroom_humidity_category
  from: 'normal'
  to: 'humid'
- platform: state
  entity_id: light.shelly02_light
  from: 'off'
  to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.people_home
      state: 'on'
action:
- service: light.turn_on
  entity_id: light.shelly02_light
- service: timer.start
  entity_id: timer.bathroom_ventilator
