#
# SHELLY 01
#
#
substitutions:
  name_shelly: Shelly01

esphome:
  name: shelly_01
  platform: ESP8266
  board: esp01_1m

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ext_ssid
      password: !secret wifi_ext_password


captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

output:
  - platform: gpio
    pin: GPIO4
    id: shelly_relay

# Sync time with Home Assistant
#time:
#  - platform: homeassistant
#    id: homeassistant_time

# Text sensors with general information
#text_sensor:
#  - platform: version
#    name: "$name_shelly version"
#  - platform: wifi_info
#    ip_address:
#      name: "$name_shelly ip"
#    ssid:
#      name: "$name_shelly ssid"
#    bssid:
#      name: "$name_shelly bssid"

#sensor:
#  - platform: wifi_signal
#    name: "$name_shelly wifi"
#    update_interval: 10s
#  - platform: uptime
#    name: "$name_shelly uptime"
                                       
light:                                 
  - platform: binary                   
    name: "$name_shelly light"              
    output: shelly_relay                     
    id: lightid                        
                                       
binary_sensor:                         
  - platform: gpio                     
    pin:                               
      number: GPIO5                    
      #mode: INPUT_PULLUP              
      #inverted: True                  
    name: "$name_shelly"             
    on_state:                          
      then:                            
        - light.toggle: lightid        
    internal: true                     
    id: switchid