# esp32: Development
#
# This is my ESP32 Camera
#
substitutions:
 name_espcamera: ESP32Camera

esphome:
  name: esp32camera
  platform: ESP32
  board: esp32dev

wifi:
  networks:
  - ssid: !secret wifi_ext_ssid
    password: !secret wifi_ext_password
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

captive_portal:

logger:

#not using a password for the API
api:
  
#not using a pwd for OTA
ota:

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: $name_espcamera Wifi
    update_interval: 10s
  - platform: uptime
    name: $name_espcamera Uptime

switch:
  - platform: restart
    name: $name_espcamera Restart

# Sync time with Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information
text_sensor:
  - platform: version
    name: $name_espcamera version
  - platform: wifi_info
    ip_address:
      name: $name_espcamera ip
    ssid:
      name: $name_espcamera ssid
    bssid:
      name: $name_espcamera bssid
      
esp32_camera:
  name: $name_espcamera
  external_clock:
    pin: GPIO32
    frequency: 20MHz
  i2c_pins:
    sda: GPIO13
    scl: GPIO12
  data_pins: [GPIO5, GPIO14, GPIO4, GPIO15, GPIO18, GPIO23, GPIO36, GPIO39]
  vsync_pin: GPIO27
  href_pin: GPIO25
  pixel_clock_pin: GPIO19
  max_framerate: 5 fps
  jpeg_quality: 10
  vertical_flip: false

i2c:
  sda: GPIO21
  scl: GPIO22
font:
  - file: "Ubuntu-Regular.ttf"
    id: ubuntu
    size: 20
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.print(0, 0, id(ubuntu), "Hello World!");

binary_sensor:
  - platform: gpio
    pin: GPIO33
    name: $name_espcamera motion
    device_class: motion