# esp32: Ground Floor Hardware
#
# This is my ESPHome ESP32 doorbell.
#
substitutions:
 esp32: ESP32_Doorbell

esphome:
  name: esp32_doorbell
  platform: ESP32
  board: esp32dev

wifi:
  networks:
    - ssid: !secret wifi_ext_ssid
      password: !secret wifi_ext_password
    - ssid: !secret wifi_ssid
      password: !secret wifi_ext_password

captive_portal:

logger:

#not using a password for the API
api:
  
#not using a pwd for OTA
ota:

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: "$esp32 Wifi"
    update_interval: 10s
  - platform: uptime
    name: "$esp32 Uptime"
 
switch:
  - platform: restart
    name: "$esp32 Restart"

# Sync time with Home Assistant
time:
  - platform: homeassistant
    id: homeassistant_time

# Text sensors with general information
text_sensor:
  - platform: version
    name: "$esp32 Version"
  - platform: wifi_info
    ip_address:
      name: "$esp32 IP"
    ssid:
      name: "$esp32 SSID"
    bssid:
      name: "$esp32 BSSID"