alias: detection_floorbedroom_during_silent_hours
trigger:
- platform: state
  entity_id: binary_sensor.foscam_floor_audio
  to: 'on'
- platform: state
  entity_id: binary_sensor.foscam_floor_motion
  to: 'on'
condition:
  condition: and
  conditions:
    - condition:
      condition: or
      conditions:
        - condition: template
          value_template: >-
            {{
            (states('input_datetime.kids_silent_hours_start')
            <
            states('sensor.time')+":00"
            and
            states('sensor.time')+":00" 
            <
            states('input_datetime.house_silent_hours_start'))
            or
            (states('input_datetime.kids_silent_hours_end')
            <
            states('sensor.time')+":00"
            and
            states('sensor.time')+":00" 
            < 
            states('input_datetime.house_silent_hours_end'))
            }}
        - condition: state
          entity_id: input_boolean.guest_mode
          state: 'On'
    - condition: state
      entity_id: timer.floor_presence_detection
      state: idle
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.foscam_floor_infrared
  - delay: 0:05
  - service: camera.snapshot
    data:
      entity_id: camera.camera_foscam_floor
      filename: "/config/www/cam_captures/floor_bedroom.jpg"
#  - service: camera.snapshot
#    data:
#      entity_id: camera.camera_foscam_floor
#      filename: "/config/www/cam_captures/floor_bedroom_{{ now ().year }}_{{ now ().month }}_{{ now ().day }}_{{ now ().hour }}_{{ now ().minute }}.jpg"
  - delay: 0:02
  - service: notify.all_devices
    data_template:
        title: Motion Detected
        message: Floors Bedroom
        data:
          sticky: true
          attachment:
            url: >-
              {{ states("input_text.system_secrets_http_fullurl") }}/local/cam_captures/floor_bedroom.jpg
            content-type: jpeg
            hide-thumbnail: false
