# This automation starts the master_room timer when 
# the light is enabled.
#
alias: start_timer_on_turn_on_light_at_floor
trigger:
- platform: state
  entity_id: switch.lcs01
  from: 'off'
  to: 'on'
condition: []
action:
- service: timer.start
  entity_id: timer.floor_bedroom_light