---
# This automation turn off the master_room light when 
# the timer is finished.
#
alias: turn_off_light_when_master_timer_finished
trigger:
- platform: event
  event_type: timer.finished
  event_data:
    entity_id: timer.floor_bedroom_light
condition: []
action:
- service: homeassistant.turn_off
  entity_id: switch.lcs01