alias: enter_creche_in_the_afternoon
trigger:
  - platform: zone
    entity_id: device_tracker.iphone_van_judith, device_tracker.iphone_van_martijn
    zone: zone.creche
    event: "enter" #or leave
condition:
  - condition: time
    after: '12:00:00'
    before: '19:00:00'
action:
  - service: notify.all_devices
    data:
      title: "Kids@Creche"
      message: "Kids are being picked-up at the creche @ {{ states('sensor.date_time') }}"
      data:
        sticky: 'false'