alias: leave_creche_in_the_morning
trigger:
  - platform: zone
    entity_id: device_tracker.iphone_van_judith, device_tracker.iphone_van_martijn
    zone: zone.creche
    event: "leave"
condition:
  - condition: time
    after: '07:00:00'
    before: '12:00:00'
action:
  - service: notify.all_devices
    data:
      title: "Kids@Creche"
      message: "Kids at the creche @ {{ states('sensor.date_time') }}"
      data:
        sticky: 'false'