---
#
# When nobody is at home make sure that:
#
# 
#
# 
alias: people_not_at_home
trigger:
  - platform: state
    entity_id: binary_sensor.people_home
    to: 'off'
action:
  - service: media_player.media_stop
    entity_id: media_player.woonkamer
  - service: media_player.turn_off
    entity_id: media_player.woonkamer
  - service: homeassistant.turn_off
    entity_id: group.master_room
  - service: homeassistant.turn_off
    entity_id: group.garden
  - service: switch.turn_off
    entity_id: group.bathroom
  - service: notify.all_devices
    data_template:
      title: "People Not@Home"
      message: "Nobody@home {{ states('sensor.date_time') }}"